### ISSUE TITLE
Compatibility Piwik 3.x.x

### ISSUE THREAD

**Issue by iMarkus** [jbrule/piwikplugin-TrackingCodeCustomizer#3] opened 2017-11-14 09:20 UTC
Hi @jbrule,

i tried this with current Piwik version 3.x.x but the plugin settings are not visible. Any plans to update the plugin?

Cheers,
iMarkus

**Comment by jbrule** [comment] 2017-11-14 23:34
They show up on my production 3.2.0 system. I will try setting up a fresh
install in Docker, hopefully some time with week, and verify. You are
looking under "Plugin Settings" in the admin?

--brulz

**Comment by iMarkus** [comment] 2017-11-15 15:19
I tried it again using a fresh 3.2.0 install. As far as I know Plugin Settings was moved to General Settings see [here](https://github.com/piwik/piwik/pull/10397)

> Plugin Settings pages
> 
> In the past we had a "User => Plugin Settings" page and an "Admin => Plugin Settings" page. We have removed both pages and now show "User => Plugin Settings" pages under "Personal Settings" and "Admin => Plugin Settings" under "General Settings". The plugin settings are now also more clearly separated from each other.

Anyhow I was not able to find the settings.

**Comment by Findus23** [comment] 2018-01-12 17:29
@jbrule In case this plugin supports Matomo 3, please change the plugin.json to 
```
   "require": {
        "piwik": ">=2.16.0,<4.0.0-b1"
    },
```
Otherwise this plugin won't appear on the marketplace for Matomo 3.

Thanks

**Comment by jbrule** [comment] 2018-01-12 19:33
@iMarkus Whoops. Sorry. I added this message to the wrong thread. I was testing this other plugin https://github.com/jbrule/piwikplugin-AdminNotification . Sorry for the confusion. I am working on getting the TrackingCodeCustomizer up to date. I should have an update in Feb.

**Comment by jbrule** [comment] 2018-01-21 17:44
Version 3 was recently released with support for Piwik/Matomo 3. You should find it in the marketplace. Please try it out.

**Comment by Findus23** [comment] 2018-01-21 17:53
@jbrule That's really great 🎉 
I tested it quickly and it seems to be working as intended.

If you want to help upgrade more plugins, take a look at my list of plugins, that don't support Matomo 3:
https://forum.matomo.org/t/adopt-a-plugin-dog/26869

**Closed as completed** 2018-01-21 17:59 UTC
